app:
    build: .
    volumes:
        - ./:/var/www
    ports:
        - 3000:80
    links:
        - mongo
    command: "npm run watch"

mongo:
  image: mongo:3.6.0-jessie
  ports:
    - 14002:27017

